#!/usr/bin/env ruby

require 'selenium-webdriver'

host = ENV['WEBDRIVER_HOST']
port = ENV['PORT'] || '4444'

begin
  driver = Selenium::WebDriver.for :remote, :url => "http://#{ host }:#{ port }/wd/hub", :desired_capabilities => :chrome
  driver.navigate.to 'http://www.docker.com'
   
  if (driver.title == "Docker - Build, Ship, and Run Any App, Anywhere")
    puts 'running okay!'
  else
    puts 'running not okay!'
  end
ensure
  driver.quit
end
